### ISSUE TITLE
Single-Business - Splash Image

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#23]
Gradient over BG of Store Picture to help with legibility

Currently:
![Screen Shot 2020-06-18 at 10 25 33 AM](https://user-images.githubusercontent.com/2172549/85046762-166c8e80-b14e-11ea-85fc-232f1c1601ab.png)

Desired
![Screen Shot 2020-06-18 at 10 24 05 AM](https://user-images.githubusercontent.com/2172549/85046700-02289180-b14e-11ea-8a6d-6aabf564ca70.png)

CSS: 
Change the <IMG> to a <DIV>

```
background: linear-gradient(360deg, rgba(0, 0, 0, 0.49) 0%, rgba(0, 0, 0, 0) 94.89%), url("http://35.160.160.218:8000/static/2_cover.jpg");
    background-size: auto, auto;
background-size: contain;

```

**Comment by sanchaymittal** [comment]
![Screenshot 2020-06-19 at 6 07 51 PM](https://user-images.githubusercontent.com/31698676/85133167-d1348380-b257-11ea-8fc9-a8d78a53a7c0.png)

**Comment by zherring** [comment]
This was not implemented? Why was this closed?

**Comment by sanchaymittal** [comment]
It is implemented... here is the commit link: https://github.com/ethifylabs/downtownstimulus/commit/56ef22bf06c69752ca1dc08c70910f44d693c43a#diff-113617fcc84b590d9f96071e78438a8aL4

**Comment by zherring** [comment]
This was implemented on the wrong element. Currently implemented on 

`.business-page-container-big`
Which is the entire background. (this is already an issue I filed to remove it here https://github.com/ethifylabs/downtownstimulus/issues/44)

This needs to be put on the image of the splash, as demonstrated above. The purpose of the gradient is for legibility - you can't read the white headlines without a gradient at the bottom of some of these images.

Would recommend changing the img tag into a div like so
![image](https://user-images.githubusercontent.com/2172549/85580736-3a6e1b00-b5f9-11ea-8bbf-a4ac922e43a5.png)
