### ISSUE TITLE
Single-Business - Business Logos

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#24]
Current
![Screen Shot 2020-06-18 at 10 27 06 AM](https://user-images.githubusercontent.com/2172549/85047027-84b15100-b14e-11ea-8c29-dcc4ed9dad67.png)

Desired
![Screen Shot 2020-06-18 at 10 27 42 AM](https://user-images.githubusercontent.com/2172549/85047054-8d098c00-b14e-11ea-9d67-0105386aec85.png)

CSS 
```
border-radius: 6px;
padding: .5rem;
background: white;
```

**Comment by sanchaymittal** [comment]
![Screenshot 2020-06-19 at 6 06 38 PM](https://user-images.githubusercontent.com/31698676/85133087-a813f300-b257-11ea-94c6-f02619e78e9d.png)
