### ISSUE TITLE
Footer - Logos of Sponsors to "Sponsored By"

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#25]
**Change Header**
From: "Logos of Sponsors" 
To: "Partners" 

![Screen Shot 2020-06-18 at 10 30 33 AM](https://user-images.githubusercontent.com/2172549/85047265-ce01a080-b14e-11ea-8066-3b6b2056846f.png)

**Currently remove all logos but:**
Gitcoin | link to Gitcoin.co
Boulder Startup Week | | link to https://boulderstartupweek.com/

**Add**
**ConsenSys Labs** | link to labs.consensys.net/
https://labs.consensys.net/static/45c707c85b9d26f5c1eb2976856974a7/af144/consensys-labs-typeface-logo-white.png

**Boulder Downtown Partnership** | link to https://www.boulderdowntown.com/
https://www.google.com/imgres?imgurl=https%3A%2F%2Fboulderstartupweek.com%2Fwp-content%2Fuploads%2F2019%2F04%2FDBP-Logo.jpg&imgrefurl=https%3A%2F%2Fboulderstartupweek.com%2Fwelcome-back-downtown-boulder-partnership-as-a-second-year-sponsor-for-boulder-startup-week%2F&tbnid=v6aTha3f2XZZiM&vet=12ahUKEwiEhp3f5ovqAhVoA50JHUWzCIkQMygBegUIARCjAQ..i&docid=ZgB021Pf7yKvJM&w=945&h=892&q=Boulder%20downtown%20business%20partnership&hl=en&ved=2ahUKEwiEhp3f5ovqAhVoA50JHUWzCIkQMygBegUIARCjAQ

**Comment by zherring** [comment]
Add Boulder Downtown Partnership Logo
https://www.google.com/imgres?imgurl=https%3A%2F%2Fboulderstartupweek.com%2Fwp-content%2Fuploads%2F2019%2F04%2FDBP-Logo.jpg&imgrefurl=https%3A%2F%2Fboulderstartupweek.com%2Fwelcome-back-downtown-boulder-partnership-as-a-second-year-sponsor-for-boulder-startup-week%2F&tbnid=v6aTha3f2XZZiM&vet=12ahUKEwiEhp3f5ovqAhVoA50JHUWzCIkQMygBegUIARCjAQ..i&docid=ZgB021Pf7yKvJM&w=945&h=892&q=Boulder%20downtown%20business%20partnership&hl=en&ved=2ahUKEwiEhp3f5ovqAhVoA50JHUWzCIkQMygBegUIARCjAQ

**Comment by sanchaymittal** [comment]
Done
![Screenshot 2020-06-19 at 6 04 48 PM](https://user-images.githubusercontent.com/31698676/85133012-8581da00-b257-11ea-9dca-715455910a84.png)

**Comment by zherring** [comment]
Change Header
From: "Logos of Sponsors"
To: "Partners"
