### ISSUE TITLE
Footer | Social Icons (under Contact and Follow)

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#26]
[contact-icos.zip](https://github.com/ethifylabs/downtownstimulus/files/4799996/contact-icos.zip)

Link email to founders@gitcoin.co
Link twitter to https://twitter.com/gitcoin
Link medium to https://medium.com/gitcoin

**Comment by sanchaymittal** [comment]
Done
![Screenshot 2020-06-19 at 6 05 07 PM](https://user-images.githubusercontent.com/31698676/85132943-6b47fc00-b257-11ea-8970-26465430122b.png)
