### ISSUE TITLE
Single Business Page - Replace Lorem Ipsum

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#27]
![image](https://user-images.githubusercontent.com/2172549/85051759-28056480-b155-11ea-854e-25bf30fe015b.png)

Change to
"Please consider supporting these other amazing Boulder businesses!"

**Comment by sanchaymittal** [comment]
Done
![Screenshot 2020-06-19 at 6 03 00 PM](https://user-images.githubusercontent.com/31698676/85132838-389e0380-b257-11ea-92df-1e4ac9bc7481.png)
