### ISSUE TITLE
footer info

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#34]
1. pls update copy here https://bits.owocki.com/2Nu5E6Q7
2. twitter => twitter.com/dtstimulus
3. help@downtownstimulus.com should be in the email footer

**Comment by sanchaymittal** [comment]
@owocki I didn't catch the first issue?
Updated the twitter and email link in footer

**Comment by owocki** [comment]
the first issue is just about updating the legal copy in the footer from lorem ipsum

**Comment by sanchaymittal** [comment]
@owocki gotcha, But we need legal info to replace it.

**Comment by owocki** [comment]
@zherring is on it!

**Comment by sanchaymittal** [comment]
Done, Will be released in upcoming patch 0.0.2
