### ISSUE TITLE
facebook app needs logo

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#35]
https://bits.owocki.com/geuw4Oen

can you also share admin privs with http://facebook.com/kevinowocki

**Comment by sanchaymittal** [comment]
@rekpero Can you check this issue.

**Comment by sanchaymittal** [comment]
Right now, we are using the personal id for firebase social auth. Will update the logo in production id.

**Comment by owocki** [comment]
https://www.facebook.com/downtownstimulus/
