### ISSUE TITLE
share modal issues

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#38]
1. link (for the link direct, twitter, fb, email ) goes to boulderfund.com not the correct url? 
https://bits.owocki.com/z8u8Plyj

**Comment by sanchaymittal** [comment]
Updated twitter & email, Need Facebook link.

**Comment by owocki** [comment]
twitter: dtstimulus
facebook.com/downtownstimulus
help@downtownstimulus.com

**Comment by rekpero** [comment]
Need your confirmation that the current change did is as expected @owocki

**Comment by owocki** [comment]
LGTM ty
