### ISSUE TITLE
no email sent after a successfsul donation

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#43]
i just donated with a test card and didnt get a confirmation email.

**Comment by Man-Jain** [comment]
The implementation is done but it can't work until we get our IP white-listed by Sendgrid

**Comment by owocki** [comment]
i havent heard anything from sendgrid and i cant login myself rn.  how can we get unblocked here?

**Comment by Man-Jain** [comment]
Done and deployed
