### ISSUE TITLE
Single Page - Change BG

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#44]
Currently
![image](https://user-images.githubusercontent.com/2172549/85315103-ab85c500-b477-11ea-802a-c8c8d3f2f472.png)

Desired:
![image](https://user-images.githubusercontent.com/2172549/85315208-d7a14600-b477-11ea-8d02-db35c94b0ed7.png)

Remove Gradient on .business-page .business-page-container-big

**Comment by rekpero** [comment]
Done and deployed in the latest patch - 0.0.1
