### ISSUE TITLE
Individual Business Page - Normalize Header Drop-Shadow

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#46]
Add same dropshadow on home page header to individual business header.

Desired:
![image](https://user-images.githubusercontent.com/2172549/85315404-3e266400-b478-11ea-9921-b1977985fb01.png)

Current: 
![image](https://user-images.githubusercontent.com/2172549/85315431-48e0f900-b478-11ea-941d-25a8b7fbd3f2.png)

**Comment by rekpero** [comment]
Done and deployed in the latest patch - 0.0.1
