### ISSUE TITLE
BUG - "How it works" modal popping up when I click on individual business first time

### ISSUE THREAD

**Issue by zherring** [ethifylabs/downtownstimulus#47]
**EXPECTED BEHAVIOR:**
Click on a business, it loads the business page.

**CURRENT BEHAVIOR:**
If first time visiting page, clicking on an individual business pulls up the "How Donation Matching Works." 

Once I close the modal, I can go to the individual business.

![image](https://user-images.githubusercontent.com/2172549/85316480-0f10f200-b47a-11ea-813b-1f4cf5993463.png)

Firefox, 77.0.1 (64-bit)

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/2172549/85316678-5dbe8c00-b47a-11ea-85da-d35974e8690d.png">

**Comment by sanchaymittal** [comment]
I thought this feature was desired, when a single business page is access for first time, we will show the modal. Maybe i miss interpreted this message.
```
Would it be possible to link to a page w/ the Quadratic Funding Modal open on load? @sanchaymittal
```

**Comment by zherring** [comment]
> I thought this feature was desired, when a single business page is access for first time, we will show the modal. Maybe i miss interpreted this message.
> 
> ```
> Would it be possible to link to a page w/ the Quadratic Funding Modal open on load? @sanchaymittal
> ```

My bad, needed to file a story for this. Intention was for this to be used only in specific circumstances, and not desired behavior every time. In case the business owners wanted to link to the explainer for QF, there is no primary page, it's just a modal, so I was thinking.

https://downtownstimulus.com/business/1
links to the main page

https://downtownstimulus.com/business/1?="qf-explain"
links to main page with modal fired already

**Comment by rekpero** [comment]
Done and deployed in the latest patch - 0.0.1
