### ISSUE TITLE
modal keeps popping up

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#49]
how come when i click ‘read more’ on a grant this modal pops up? 
https://bits.owocki.com/7KumoQGP

shouldnt it only pop up when a user specifically asks how the donation matching works

**Comment by zherring** [comment]
Also referenced here
https://github.com/ethifylabs/downtownstimulus/issues/47

**Comment by rekpero** [comment]
Done and deployed in the latest patch - 0.0.1
Reference #47
