### ISSUE TITLE
cant login via facebook

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#60]
see movie: https://bits.owocki.com/BluOdLDp

latest chrome, adblock off. just nothing hapens

**Comment by zherring** [comment]
This still is not working for me, tried it in Chrome, Firefox, and 

**This needs to be prioritized.**

**Comment by owocki** [comment]
i sent the new firebase login to @sanchaymittal yesterday, as i understand it this was the blocker?

**Comment by sanchaymittal** [comment]
it should work now.

**Comment by owocki** [comment]
did you test? i cant get it to work @sanchaymittal @zherring 

screencast: https://bits.owocki.com/P8ueQDKv

**Comment by owocki** [comment]
ok it seems that zach just explained the fb / google firebase issue sto me
