### ISSUE TITLE
can we add something to the header about how the round has started

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#63]
screenshot: https://bits.owocki.com/mXuAJmX6

add this text module to the header:

H3: $25k Pilot Round Live Now
H4: Contribute by July 15th 2020 to get your contribution Matched!

**Comment by owocki** [comment]
@sanchaymittal could we add this text real quick?

**Comment by owocki** [comment]
hey @sanchaymittal i see this is closed by i dont see it live? https://downtownstimulus.com/

**Comment by sanchaymittal** [comment]
@owocki It will up with next docker pull
