### ISSUE TITLE
downtown stimulus emails should NOT come from gitcoin.co.

### ISSUE THREAD

**Issue by owocki** [ethifylabs/downtownstimulus#74]
https://bits.owocki.com/yAuY1Po5

it should come from "from name" "downtown stimulus" , and the reply to email shoould be help@downtownstimulus.com

**Comment by sanchaymittal** [comment]
Right now, we are using the SendGrid id you shared earlier with me. I will create a new Sendgrid account using the above main and then replace it for production.

**Comment by owocki** [comment]
wait, but this has to do with the 'from_name' passed into the sendgrid API than the API keys i think right?  you can edit the from_name on a per email basis in my experience with sendgrid

**Comment by sanchaymittal** [comment]
Ohhh is that so, Let me try updating it once.

**Comment by Man-Jain** [comment]
Done ![photo_2020-06-30_22-27-02](https://user-images.githubusercontent.com/12700384/86154570-e2677500-bb20-11ea-9d30-93b8f5b15189.jpg)
