### ISSUE TITLE
Facebook Login using Firebase is acting wierd

### ISSUE THREAD

**Issue by sanchaymittal** [ethifylabs/downtownstimulus#86]
Hi! We just went to try and make a donation for the downtown stimulus and when we had to verify our information via Facebook or google the page never opened. Have any of you tried to do this yet and have you had better luck? It might just be my phone/account but I thought I would mention it in case other people run into the same thing

From: Julie Perington

**Comment by zherring** [comment]
Until this is fixed, we need to switch the order 

from FB then Google
to Google and then FB

A ton of people are getting tripped up on this it sounds like.

If this is going to be a longer fix (~24+ hours) may recommend hiding the FB option for now

![image](https://user-images.githubusercontent.com/2172549/86301002-eeefda00-bbc1-11ea-81f4-294d4657e2b5.png)
